### ISSUE TITLE
NMUIDI throws me error messages when deleting on Windows 10

### ISSUE THREAD

**Issue by blaziter** [Dillonb/nmuidi#15]
# 📝 Description

When I use nmuidi it throws me error messages when deleting but folders and files are deleted without a problem.

|  |  |
|  ------------- | -------------  |
| OS | Windows 10 Pro 22H2 |
| Build | 19045.4412 |
| RAM | 32 GB |

---

### cmd example

```bash
nmuidi node_modules\
 Cleaning node_modules\
 ERROR nmuidi::nmuidi > Failed to remove file node_modules\...\trace-mapping: Access is denied. (os error 5)
```

### Example

![image](https://github.com/Dillonb/nmuidi/assets/85119621/ca6f8de8-dd60-49e8-8ada-dda9ff45ff11)

**Comment by brasky** [comment]
@blaziter This could be a few issues. It could be antivirus like Windows Defender or a third party one, you can try [this ](https://github.com/rust-lang/cargo/issues/11544#issuecomment-1763714763) to see if that's the issue.


It could also be that those files are still in use, I'm pretty sure Windows will sometimes give you this error in that case. If you run into this issue you can run [Handle](https://learn.microsoft.com/en-us/sysinternals/downloads/handle) and look to see if there is a process holding a lock on one of those files.
