### ISSUE TITLE
Download link is 404

### ISSUE THREAD

**Issue by dezchai** [Dillonb/nmuidi#16]
https://nightly.link/Dillonb/nmuidi/workflows/build/main/nmuidi-windows.zip
![image](https://github.com/user-attachments/assets/897b9c18-167a-4ef4-8d14-baa2bc944aee)

**Comment by Dillonb** [comment]
Thanks, I kicked off another actions run to refresh the artifact. I'll publish it to Releases later so it doesn't expire again
